### ISSUE TITLE
changing from dsc to cassandra package

### ISSUE THREAD

**Issue by booo** [gini/puppet-cassandra#1]
Do you think we could change the module to use the cassandra package instead of the dsc package? As far as I understand the dsc package contains the opscenter that I do not want to install on every machine. Apart from that there is a dependency problem in ubuntu if I try to use the dsc package. Cassandra version is 1.2 but dsc depends on an earlier version of cassandra.

Best Regards
Philipp

**Comment by joschi** [comment]
The purpose of this Puppet module is to install the Datastax Community Edition which happens to include Cassandra.

Currently the module by default installs `dsc1.1` which still contains Cassandra 1.1.x. You can override this by setting the `$package_name` parameter on the `cassandra` class.

I will also update the default package to `dsc12` in the near future and release an updated module.
