### ISSUE TITLE
smarchive/cassandra listing on Puppet Forge lists centos/rhel/fedora but is explicitly not supported.

### ISSUE THREAD

**Issue by clstokes** [gini/puppet-cassandra#16]
The smarchive/cassandra listing on Puppet Forge is tagged with centos, rhel, and fedora but is explicitly not supported. Can you remove these tags?

Also, any reason both smarchive/cassandra and gini/cassandra should exist when they seem to be created and/or maintained by the same people?

**Comment by joschi** [comment]
Hi Cameron, you're completely right about the tags for the old [smarchive/cassandra](http://forge.puppetlabs.com/smarchive/cassandra) module. I've removed the Red Hat related tags as they were misleading about the capabilities of the module.

Regarding the "duplicate" modules {gini,smarchive}/cassandra it is currently not possible to either delete a module, a complete namespace ("smarchive" in this case), or to mark the module as deprecated. So the only possibility is probably to render the old module unusable by issuing a `fail()` or at least a `warning()` inside the main class.
