### ISSUE TITLE
[Question] Token assignement to nodes

### ISSUE THREAD

**Issue by msimonin** [gini/puppet-cassandra#7]
Hi, 

If I define my class using : 

```
class { 'cassandra':
    cluster_name  => 'YourCassandraCluster',
    seeds         => [ '192.0.2.5', '192.0.2.23', '192.0.2.42', ],
```

}

How tokens will be assigned to nodes ? Are they automatically assigned by cassandra during the bootstrap ? 

Best Regards,

Matt

**Comment by joschi** [comment]
Hi Matt,

the intial tokens have been "superseeded" by virtual nodes (vnodes) in Cassandra 1.2. You don't need and actually should not set an initial token in Cassandra 1.2 or higher.

Relevant documentation links are the following:
- http://www.datastax.com/docs/1.2/initialize/token_generation
- www.datastax.com/documentation/cassandra/1.2/cassandra/architecture/architectureDataDistributeVnodesUsing_c.html
- http://www.datastax.com/dev/blog/upgrading-an-existing-cluster-to-vnodes-2

You can still use an older version of Cassandra (or the complete DSC) with this Puppet module but the default is currently Cassandra 1.2 if you don't set any additional class parameters (please refer to `init.pp`).

Best regards,
Jochen

**Comment by msimonin** [comment]
Thank you very much for your answer. 
The documentation was usefull.

Matt

**Comment by joschi** [comment]
Glad I could help.

This said, we should really improve the documentation of this Puppet module…
